INSERT INTO master_data ("type", "key", "value") VALUES ('gender', 'M', 'Male');
INSERT INTO master_data ("type", "key", "value") VALUES ('gender', 'F', 'Female');

INSERT INTO master_data ("type", "key", "value") VALUES ('education_level', '01', '১ম শ্রেনী');
INSERT INTO master_data ("type", "key", "value") VALUES ('education_level', '02', '২য় শ্রেনী');

INSERT INTO master_data ("type", "key", "value") VALUES ('occupation', '02', 'ইঞ্জিনিয়ারিং ও স্থপতি');
INSERT INTO master_data ("type", "key", "value") VALUES ('occupation', '03', 'ইঞ্জিনিয়ারিং ও স্থপতি সম্পর্কিত টেকনিশিয়ান');

INSERT INTO master_data ("type", "key", "value") VALUES ('marital_status', '1', 'un-married');
INSERT INTO master_data ("type", "key", "value") VALUES ('marital_status', '2', 'married');

INSERT INTO master_data ("type", "key", "value") VALUES ('country_code', '050', 'Bangladesh');
INSERT INTO master_data ("type", "key", "value") VALUES ('country_code', '051', 'Armenia');

INSERT INTO master_data ("type", "key", "value") VALUES ('relations', 'FTH', 'father');
INSERT INTO master_data ("type", "key", "value") VALUES ('relations', 'SPS', 'spouse');

INSERT INTO master_data ("type", "key", "value") VALUES ('religion', '1', 'islam');
INSERT INTO master_data ("type", "key", "value") VALUES ('religion', '2', 'hindu');

INSERT INTO master_data ("type", "key", "value") VALUES ('blood_group', '5', 'B+');
INSERT INTO master_data ("type", "key", "value") VALUES ('blood_group', '6', 'B-');

INSERT INTO master_data ("type", "key", "value") VALUES ('disability', '0', 'সমস্যা নেই');
INSERT INTO master_data ("type", "key", "value") VALUES ('disability', '1', 'বাক');

INSERT INTO master_data ("type", "key", "value") VALUES ('status', '1', 'Alive');
INSERT INTO master_data ("type", "key", "value") VALUES ('status', '2', 'Deceased');
INSERT INTO master_data ("type", "key", "value") VALUES ('status', '3', 'Unknown');