INSERT INTO approval_fields ("field", "option") VALUES ('gender', 'NA');
INSERT INTO approval_fields ("field", "option") VALUES ('given_name', 'NA');
INSERT INTO approval_fields ("field", "option") VALUES ('occupation', 'NA');
INSERT INTO approval_fields ("field", "option") VALUES ('phone_number', 'NA');
INSERT INTO approval_fields ("field", "option") VALUES ('present_address', 'NA');
INSERT INTO approval_fields ("field", "option") VALUES ('status', 'NA');
INSERT INTO approval_fields ("field", "option") VALUES ('date_of_death', 'NA');