#!/bin/bash
#
# mci        start/stop/status script
#
# chkconfig: - 64 36
# description: The mci shared health record system
# processname: mci
# config: /etc/default/mci
# pidfile: /var/run/mci/mci.pid
### BEGIN INIT INFO
# Provides: mci
# Required-Start: $local_fs $remote_fs $network $named $syslog $time
# Required-Stop: $local_fs $remote_fs $network $named $syslog $time
# Short-Description: start and stop mci system,
# Description: BDSHR system
### END INIT INFO

export MCI_USER=sharedhealth
export MCI_RUN=/opt/mci/bin/start.sh
export CUR_USER=`/usr/bin/whoami`

# load configuration
. /etc/default/mci

create_dirs() {
    if [[ ! -e /var/run/mci ]]; then
        ln -s /opt/mci/var /var/run/mci
    fi

    if [[ ! -e /var/log/mci ]]; then
        mkdir /var/log/mci
    fi
}
mci_pid() {
        echo `ps -fe | grep 'mci-api.war' | grep -v grep | tr -s " "|cut -d" " -f2`
}

start(){
    pid=$(mci_pid)
    if [ -n "$pid" ];
    then
        echo -e "\e[00;31mService mci is already running (pid: $pid)\e[00m"
    else
        # Start mci
        create_dirs
        echo -e "\e[00;32mStarting mci\e[00m"
        if [ `user_exists $MCI_USER` = "1" ] && [ "$CUR_USER" != "$MCI_USER" ] ;
        then
                /bin/su $MCI_USER -c $MCI_RUN
        else
                sh $MCI_RUN
        fi
  fi
  return 0
}
status(){
          pid=$(mci_pid)
          if [ -n "$pid" ]; then echo -e "\e[00;32mService mci is running with pid: $pid\e[00m"
          else echo -e "\e[00;31mService mci is not running\e[00m"
          fi
}

stop() {
	echo -e "\e[00;31mTerminating mci\e[00m"
	kill -9 $(mci_pid)
}
user_exists(){
        if id -u $1 >/dev/null 2>&1; then
        echo "1"
        else
                echo "0"
        fi
}

case $1 in
	start)
	  start
	;;
	stop)
	  stop
	;;
	restart)
	  stop
	  start
	;;
	status)
		status
	;;
	kill)
		stop
	;;
	*)

	;;
esac
exit 0